### ISSUE TITLE
Unexpected behaviour for `GFF3.strand`

### ISSUE THREAD

**Issue by lysogeny** [BioJulia/GFF3.jl#5]
When given an unstranded feature, `strand` doesn't return the expected results.

GFF3 specifies that features where `strand` is `.` are unstranded (https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md):

> Column 7: "strand"
>     The strand of the feature. + for positive strand (relative to the landmark), - for minus strand, and . for features that are not stranded. In addition, ? can be used for features whose strandedness is relevant, but unknown

Thus, when using `GFF3.strand` on an unstranded feature (like a chromosome) I would expect it to return a `GenomicFeatures.STRAND_BOTH`. Instead the function raises an error.

## Expected Behavior

```julia
genome_file = "genomes/Mus_musculus.GRCm38.102.gff3.gz"
reader = open(genome_file, "r") |> GzipDecompressorStream |> GFF3.Reader
record = read(reader)
GFF3.strand(record)
```
returns
```
STRAND_BOTH
```

## Current Behavior

```julia
genome_file = "genomes/Mus_musculus.GRCm38.102.gff3.gz"
reader = open(genome_file, "r") |> GzipDecompressorStream |> GFF3.Reader
record = read(reader)
GFF3.strand(record)
```
returns
```
ERROR: strand is missing
Stacktrace:
 [1] missingerror(field::Symbol)
   @ BioCore.Exceptions ~/.julia/packages/BioCore/YBJvb/src/Exceptions.jl:22
 [2] strand(record::GFF3.Record)
   @ GFF3 ~/.julia/packages/GFF3/b3VT6/src/record.jl:363
 [3] top-level scope
   @ REPL[66]:1
```

## Possible Solution / Implementation

The implementation checks if the field is missing (i.e. set to `.` or `0x2e`):
https://github.com/BioJulia/GFF3.jl/blob/76809cc71320cb9d67f0f5794cfe07d4cf1a36df/src/record.jl#L361
Handling a missing field by returning `GenomicFeatures.STRAND_BOTH` should produce the expected results.

## Other

If there is some reason for this behaviour which is not obvious to me, please tell me and I will gladly be put into my place.
For me, this makes my code more complicated than it has to be, as I have to perform extra checks to see if something is unstranded.

Further, whether this should also apply to `GFF3.phase` is also a question, as that function also checks this. Here however a `.` is not specified to mean anything, so likely this shouldn't apply.

**Comment by CiaranOMara** [comment]
There are 3 kinds of records in GFF3.
https://github.com/BioJulia/GFF3.jl/blob/b0da4b74a0fc8f5abe9ec4d153f3ee4dfbef7cbb/src/reader.jl#L218

I think the strand is column mandatory for a feature, though the strand column would not be present for a comment or a directive. But, comments and directives should be skipped by default.

What does `record.kind` show, and would you be able to provide a link to the Mus_musculus.GRCm38.102.gff3.gz file so that I can have a better look?

**Comment by CiaranOMara** [comment]
The file can be found at ftp://ftp.ensembl.org/pub/release-102/gff3/mus_musculus//Mus_musculus.GRCm38.102.gff3.gz

```julia
julia> reader = open(genome_file, "r") |> GzipDecompressorStream |> GFF3.Reader
GFF3.Reader(BioCore.Ragel.State{BufferedStreams.BufferedInputStream{TranscodingStreams.TranscodingStream{GzipDecompressor, IOStream}}}(BufferedStreams.BufferedInputStream{TranscodingStreams.TranscodingStream{GzipDecompressor, IOStream}}(<128.0 KiB buffer, 0% filled>), 1, 1, false), nothing, false, [:feature], false, GFF3.Record[], 0, 0)

julia> record = read(reader)
GFF3.Record:
       seqid: 1
      source: GRCm38
        type: chromosome
       start: 1
         end: 195471971
       score: <missing>
      strand: <missing>
       phase: <missing>
  attributes: ID=chromosome:1 Alias=CM000994.2,NC_000067.6,chr1

julia> str = String(record.data)
"1\tGRCm38\tchromosome\t1\t195471971\t.\t.\t.\tID=chromosome:1;Alias=CM000994.2,NC_000067.6,chr1"

julia> str[record.strand]
'.': ASCII/Unicode U+002E (category Po: Punctuation, other)

julia> fields = split(str, '\t')
9-element Vector{SubString{String}}:
 "1"
 "GRCm38"
 "chromosome"
 "1"
 "195471971"
 "."
 "."
 "."
 "ID=chromosome:1;Alias=CM000994.2,NC_000067.6,chr1"
```

**Comment by CiaranOMara** [comment]
In GFF3 files the `.` is used to represent missing values. However, the `ismissing` logic for `strand` in this package is faulty.

https://github.com/BioJulia/GFF3.jl/blob/b0da4b74a0fc8f5abe9ec4d153f3ee4dfbef7cbb/src/record.jl#L482-L488

https://github.com/BioJulia/GFF3.jl/blob/b0da4b74a0fc8f5abe9ec4d153f3ee4dfbef7cbb/src/record.jl#L358-L365
